export const metadata = {
  title: "SARD | ADMIN",
  description: "Generated by Sanity ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
